import 'dart:io';
import '../utils/file_validator.dart';
import 'download_status.dart';

class DownloadItem {
  DownloadItem({
    required this.taskId,
    required this.url,
    required this.fileName,
    MediaType? mediaType,
    this.status = DownloadStatus.queued,
    this.progress = 0,
    this.savedDir,
    this.openWithSystemApp = true,
  }) : mediaType = mediaType ?? FileValidator.getMediaType(fileName.isNotEmpty ? fileName : url);

  /// String task ID generated by flutter_downloader
  String taskId;
  final String url;
  final String fileName;
  final MediaType mediaType;
  DownloadStatus status;
  int progress;
  String? savedDir;

  /// Open mode toggle: true = Open with External App/Gallery (Default), false = In-App Viewer
  bool openWithSystemApp;

  /// Full filesystem path to the downloaded file if savedDir is present
  String? get filePath {
    if (savedDir == null || savedDir!.isEmpty) return null;
    final separator = savedDir!.endsWith('/') || savedDir!.endsWith('\\') ? '' : '/';
    final primaryPath = '$savedDir$separator$fileName';
    if (File(primaryPath).existsSync()) {
      return primaryPath;
    }
    final candidatePaths = [
      '/storage/emulated/0/Download/$fileName',
      '/storage/emulated/0/Pictures/$fileName',
      '/storage/emulated/0/Movies/$fileName',
    ];
    for (final path in candidatePaths) {
      if (File(path).existsSync()) {
        return path;
      }
    }
    return primaryPath;
  }

  bool get isCompleted => status == DownloadStatus.completed;
  bool get isDownloading => status == DownloadStatus.downloading;
  bool get isPaused => status == DownloadStatus.paused;
  bool get isFailed => status == DownloadStatus.failed;

  bool get isImage => mediaType == MediaType.image;
  bool get isVideo => mediaType == MediaType.video;
}
